### ISSUE TITLE
Removed props don't get unsubscribed

### ISSUE THREAD

**Issue by Andarist** [erikras/react-callbag-listener#1]
Correct me if I'm wrong (I'm already sleepy 😉), but I think if we remove a props between renders old (removed) prop/callbag won't get unsubscribed, because you only iterate through current props in the `componentDidUpdate` hook.

**Comment by erikras** [comment]
That was the point of [this test](https://github.com/erikras/react-callbag-listener/blob/master/src/ReactCallbagListener.test.js#L93-L122). Do you still think this is an issue?

**Comment by Andarist** [comment]
This test indeed unsubscribes from a callbag but in a different situation. Imagine other scenario:
```js
const props = this.props.smth % 2 === 0
  ? { first: callbagOne }
  : { second: callbagTwo }
return (
  <ReactCallbagListener {...props}>
    {() => <div />}
</ReactCallbagListener>
)
```

`first` won't get unsubscribed when it stops being used, as its under non-existing key in `this.props` after a re-render.

**Comment by erikras** [comment]
Duh. I was going to do this, but then I forgot. Good eye! 👍
